### ISSUE TITLE
Add uploading property to six-file-upload

### ISSUE THREAD

**Issue by franckdervaux** [six-group/six-webcomponents#202]
### What problem does this feature solve?

In order to give the end-user some feedback when he is uploading a file, the six-file-upload should be able to show a spinner during the upload operation.

### What does the proposed API look like?

Add an `uploading` boolean property to the `six-file-upload`. It would default to `false`. Whilst it is `true` the component would show  a `six-spinner` instead of its label and input, and dropping or selecting a file would be disabled.

**Comment by franckdervaux** [comment]
I would like to publish a PR with this change implemented, but it seems I am not permissioned to push a branch to that repo?

**Comment by colinscz** [comment]
Hi @franckdervaux 
You cannot push directly to this repository, in order to contribute you need to fork the repository, commit the changes there and then propose the changes via pull request. 
In the github docs here it's fully explained: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo
